version: "3.8"

volumes:
  db_data: {}

services:
  db:
    image: mongo:4.4.0
    volumes:
      - db_data:/data/db
    restart: always
    container_name: "mongodb"
    ports:
      - "27017:27017"

  beer-daisuki:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: beer-daisuki:latest
    container_name: "beer-daisuki"
    ports:
      - "3000:3000"
    command: npm run start
